In [21]:
import numpy as np

## Q#1: Create x array with elements equal to 1.

In [15]:
x= np.ones(shape=(5, ))
x

array([1., 1., 1., 1., 1.])

## Q#2: Create y array with elements equal to 0.

In [17]:
y=np.zeros(shape=(5, ))
y

array([0., 0., 0., 0., 0.])

## Q#3: Add x and y arrays.

In [23]:
z = x + y
z

array([1., 1., 1., 1., 1.])

## Q#4: Print x array characteristics (e.g: dimension, shape, size, type).

In [24]:
print("Shape:", x.shape)
print("Data Type:", x.dtype)
print("Number of Dimensions:", x.ndim)
print("Number of Elements:", x.size)

Shape: (5,)
Data Type: float64
Number of Dimensions: 1
Number of Elements: 5


## Q#5: Create a 2D array "called w" as the following:

|       |          |
| ----- | -------- |
| 11    | 12       |
| 13    | 14       |
| 15    | 16       |


In [26]:
w= np.array([[11,12],[13,14],[15,16]])
w

array([[11, 12],
       [13, 14],
       [15, 16]])

## Q#6: Create z array contains the numbers from 1 to 3.

In [27]:
z= np.array ([1,2,3])
z

array([1, 2, 3])

## Q#7: Combine the arrays z and w in horizontal way then save it in a new variable "newArray".

In [40]:
z

array([[1],
       [2],
       [3]])

In [43]:
new_array= np.column_stack((w,z))
new_array

array([[11, 12,  1],
       [13, 14,  2],
       [15, 16,  3]])

## Q#8: Print all elements of "newArray" using the loop.

In [45]:
new_array = np.array([[11, 12, 1],
                     [13, 14, 2],
                     [15, 16, 3]])
for row in new_array:
    for element in row:
        print(element)

11
12
1
13
14
2
15
16
3


## Q#9: Reverse the columns and rows of "newArray".

In [46]:
reversed_array = new_array[::-1, ::-1]
reversed_array

array([[ 3, 16, 15],
       [ 2, 14, 13],
       [ 1, 12, 11]])

## Q#10: Decrement all elements of "newArray" with 1.

In [47]:
new_array -= 1
new_array 

array([[10, 11,  0],
       [12, 13,  1],
       [14, 15,  2]])

## Q#11: Find smallest and biggest values in "newArray".

In [52]:
smallest_value = np.min(new_array)
largest_value = np.max(new_array)

smallest_value

largest_value

15

## Q#12: Print the first row of "newArray" using indexing.

In [53]:
first_row = new_array[0]
first_row 


array([10, 11,  0])

## Q#13: Print the number equals 12 of "newArray" using indexing.

In [58]:
element_12 = new_array[0, 1]
element_12

11

## Q#14: Print the numbers equal 0 and 13 of "newArray" using indexing.

In [61]:
element_0 = new_array[0, 2]
element_13 = new_array[1, 0]

element_0
element_13

12

## Q#15: Change the shape of "newArray" to (9,1).

In [62]:
reshaped_array = new_array.reshape(9, 1)
reshaped_array

array([[10],
       [11],
       [ 0],
       [12],
       [13],
       [ 1],
       [14],
       [15],
       [ 2]])

## Q#16: Change the shape of "newArray" to (3,2).

In [63]:
reshaped_array = new_array.reshape(3, 3)
reshaped_array

array([[10, 11,  0],
       [12, 13,  1],
       [14, 15,  2]])

# Well Done 🎉